### ISSUE TITLE
[SOL-62310] Default binding properties are ignored when both binding-specific properties and multi-binder environment are defined

### ISSUE THREAD

**Issue by Mrc0113** [SolaceProducts/solace-spring-cloud#29] opened 2020-10-01 16:36 UTC
Hi, 

When I tried setting a prefix under `spring.cloud.stream.solace.default.consumer.prefix`on the Cloud Stream Binder and also had `queueAdditionalSubscriptions` on my binding the prefix was not properly applied. Note that it works successfully if I don't have `queueAdditionalSubscriptions` or if I specify the prefix on specific bindings such as `spring.cloud.stream.solace.bindings.uppercase-in-0.consumer.prefix=my/prefix/`.

Just a guess, but when debugging I found that prefix was empty when it got to the queue provisioner so I'm thinking that potentially somehow the definition of queueAdditionalSubscriptions is wiping out properties defined under default? 

Example Config below resulted in queue name of `uppercase.group` instead of expected `my/prefix/uppercase.group`: 
```
spring.cloud.function.definition=uppercase
spring.cloud.stream.bindings.uppercase-in-0.destination=uppercase
spring.cloud.stream.bindings.uppercase-in-0.group=group
spring.cloud.stream.bindings.uppercase-out-0.destination=output/topic
spring.cloud.stream.solace.bindings.uppercase-in-0.consumer.queueAdditionalSubscriptions=spring/sample/uppercase
spring.cloud.stream.solace.default.consumer.prefix=my/prefix/ 
```  

My version info (pom generated from start.spring.io): 
```
	<properties>
		<java.version>11</java.version>
		<solace-spring-cloud.version>1.1.1</solace-spring-cloud.version>
		<spring-cloud.version>Hoxton.SR8</spring-cloud.version>
	</properties>
```

App code just has a single function: 
```
	@Bean
	public Function<String, String> uppercase(){
		return v -> {
			System.out.println("Uppercasing "+ v);
			return v.toUpperCase();
		};
	}
```

**Comment by PhilippeKhalife** [comment] 2021-10-19 18:20
Reviewed, leaving in current state.

**Comment by elliotBraem** [comment] 2022-01-03 20:35
Why is this being left in current state? Having the ability to default consumer and producer properties is very convenient and was possible in older solace versions, otherwise I am duplicating all of my configurations for each one. What's the reasoning?

**Comment by Nephery** [comment] 2022-01-05 19:54
@Mrc0113 @elliotBraem After a lot of trial and error I was finally able to reproduce the bug.

This bug specifically occurs when both `spring.cloud.stream.<binder>.bindings.<binding>.consumer/producer.<property>` and `spring.cloud.stream.binders.<custom-binder-name>.environment.<property>` are defined in your `application.properties` file. In which case, default properties are ignored.

I was able to reproduce the issue with the Rabbit binder as well, so I'm not sure if this is something we can/should fix in our binder or at the framework level. For the time being I've raised https://github.com/spring-cloud/spring-cloud-stream/issues/2262.

**Comment by Mrc0113** [comment] 2022-01-05 19:57
Thanks for looking into this @Nephery. I can now see why it wasn't easy to reproduce previously and why it seemed to be working for others and not me 🤣

**Comment by elliotBraem** [comment] 2022-01-05 20:08
Ahhhh thank you so much for looking into this @Nephery . I see that configuration in mine as well... Makes much more sense now. 

Maybe this shouldn't be fixed in the binder level, but I think @Mrc0113 and I both ran into this issue because this is how the configuration is presented in documentation. Do with that what you will! 

Thanks again!!

**Comment by Nephery** [comment] 2023-01-13 17:44
https://github.com/spring-cloud/spring-cloud-stream/issues/2262 is resolved now. I'll close this bug once we point the build for this project to the next Spring Cloud version.

**Comment by carolmorneau** [comment] 2023-04-25 13:48
Closing as this project is now pointing to Spring Cloud 2021.0.6

**Closed by carolmorneau** 2023-04-25 13:48 UTC
Labels: bug, help wanted, tracked
