### ISSUE TITLE
Spring Boot 3 incompatibility, (required a bean of type 'org.springframework.cloud.stream.function.StreamBridge' that could not be found.)

### ISSUE THREAD

**Issue by siavashingka** [SolaceProducts/solace-spring-cloud#221] opened 2023-05-01 09:48 UTC
I cannot use `StreamBridge` class with Spring boot 3
These are my dependencies:
```
plugins {
    id("org.springframework.boot") version "3.0.6"
    id("io.spring.dependency-management") version "1.1.0"
    kotlin("jvm") version "1.7.22"
    kotlin("plugin.spring") version "1.7.22"
}

repositories {
    mavenCentral()
}

extra["springCloudVersion"] = "2022.0.2"

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("com.solace.spring.cloud:spring-cloud-stream-binder-solace:3.4.0")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    testImplementation("org.springframework.cloud:spring-cloud-stream") {
        artifact {
            name = "spring-cloud-stream"
            extension = "jar"
            type = "test-jar"
            classifier = "test-binder"
        }
    }
    testImplementation("io.mockk:mockk:1.13.5")
}
```

When I try to autowire the `StreamBridge` object to use it as a medium for publishing directly it fails wit this error:

```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-05-01T11:36:18.651+02:00 ERROR 59777 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.ingka.solacescs.TestController required a bean of type 'org.springframework.cloud.stream.function.StreamBridge' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.cloud.stream.function.StreamBridge' in your configuration.
```

And when I rollback the Spring boot version to `2.7.3` the problem disappears, so most probably is incompatibility issue.

**Also, I would appreciate if someone can tell me a workaround in the meantime of solving the root cause.**

UPDATE:
I see this in the `StreamBridge` docs:
/**
 * A class which allows user to send data to an output binding.
 * While in a common scenario of a typical spring-cloud-stream application user rarely
 * has to manually send data, there are times when the sources of data are outside of
 * spring-cloud-stream context and therefore we need to bridge such foreign sources
 * with spring-cloud-stream.
 * <br><br>
 * This utility class allows user to do just that - <i>bridge non-spring-cloud-stream applications
 * with spring-cloud-stream</i> by providing a mechanism (bridge) to send data to an output binding while
 * maintaining the  same invocation contract (i.e., type conversion, partitioning etc) as if it was
 * done through a declared function.
 *
 * @author Oleg Zhurakousky
 * @author Soby Chacko
 * @since 3.0.3
 *
 */

How can I directly publish on Solace then?

**Comment by Mrc0113** [comment] 2023-05-02 18:55
Hi @siavashingka, 

I'm assuming the root cause here is that Solace hasn't published a binder version compatible with Spring Boot 3. The latest release is compatible with Spring boot v2.7.11. 

https://github.com/SolaceProducts/solace-spring-cloud/releases/tag/2.5.0

**Comment by Nephery** [comment] 2023-05-18 14:31
Closing issue with #227 . The 3.0.0 release will be compatible with Spring Boot 3.x & Spring Cloud 2022.x.

**Closed by Nephery** 2023-05-18 14:31 UTC
